version: '3.8'

services:
  ftn:
    image: ghcr.io/ftn-io/ftn:latest
    container_name: ftn
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FTN_API_KEY=${FTN_API_KEY}
      - FTN_API_URL=${FTN_API_URL}
      - FTN_DB_URL=${FTN_DB_URL}
      - FTN_DB_USER=${FTN_DB_USER}
      - FTN_DB_PASSWORD=${FTN_DB_PASSWORD}
      - FTN_LOG_LEVEL=${FTN_LOG_LEVEL}
    volumes:
      - ./data:/data
    networks:
      - ftn_network
    depends_on:
      - db
  ftn-worker:
    image: ghcr.io/ftn-io/ftn-worker:latest
    container_name: ftn_worker
    restart: unless-stopped
    environment:
      - FTN_API_KEY=${FTN_API_KEY}
      - FTN_API_URL=${FTN_API_URL}
      - FTN_DB_URL=${FTN_DB_URL}
      - FTN_DB_USER=${FTN_DB_USER}
      - FTN_DB_PASSWORD=${FTN_DB_PASSWORD}
      - FTN_LOG_LEVEL=${FTN_LOG_LEVEL}
    networks:
      - ftn_network
    depends_on:
      - ftn
      - db
  db:
    image: postgres:latest
    container_name: ftn_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${FTN_DB_USER}
      - POSTGRES_PASSWORD=${FTN_DB_PASSWORD}
      - POSTGRES_DB=ftn
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - ftn_network
networks:
  ftn_network:
    driver: bridge
volumes:
  db_data:
    driver: local
  data:
    driver: local